global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Carbon Tracker API
  - job_name: 'carbon-api'
    static_configs:
      - targets: ['carbon-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Kafka metrics
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']

  # InfluxDB metrics
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
    metrics_path: '/metrics'

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Flink metrics
  - job_name: 'flink'
    static_configs:
      - targets: ['flink-jobmanager:8081']
    metrics_path: '/metrics'

  # Node exporter (if available)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Custom application metrics
  - job_name: 'carbon-metrics'
    static_configs:
      - targets: ['carbon-api:8000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s