apiVersion: v1
kind: Namespace
metadata:
  name: carbon-tracker
  labels:
    name: carbon-tracker
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: carbon-tracker-quota
  namespace: carbon-tracker
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: carbon-tracker-limits
  namespace: carbon-tracker
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container